### ISSUE TITLE
ISPDB Entry - Changes Needed for umich.edu

### ISSUE THREAD

**Issue by umichbcors** [thundernest/autoconfig#34] opened 2022-06-27 18:25 UTC
Hello.

We need to change the following XML file for umich.edu in the ISP Database:
https://autoconfig.thunderbird.net/v1.1/umich.edu

The new version needs to be as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<clientConfig version="1.1">
	<emailProvider id="umich.edu">
		<domain>umich.edu</domain>
		<displayName>University of Michigan</displayName>
		<displayShortName>umich.edu</displayShortName>
		<incomingServer type="imap">
			<hostname>imap.gmail.com</hostname>
			<port>993</port>
			<socketType>SSL</socketType>
			<username>%EMAILADDRESS%</username>
			<authentication>OAuth2</authentication>
			<authentication>password-cleartext</authentication>
		</incomingServer>
		<outgoingServer type="smtp">
			<hostname>smtp.gmail.com</hostname>
			<port>465</port>
			<socketType>SSL</socketType>
			<username>%EMAILADDRESS%</username>
			<authentication>OAuth2</authentication>
			<authentication>password-cleartext</authentication>
		</outgoingServer>
	</emailProvider>

	<oAuth2>
		<issuer>accounts.google.com</issuer>
		<!--  https://developers.google.com/identity/protocols/oauth2/scopes  -->
			<scope>https://mail.google.com/ https://www.googleapis.com/auth/contacts https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/carddav</scope>
			<authURL>https://accounts.google.com/o/oauth2/auth</authURL>
			<tokenURL>https://www.googleapis.com/oauth2/v3/token</tokenURL>
	</oAuth2>
</clientConfig>
```

I believe I have submitted the needed pull request here; can someone please confirm this will be reviewed and changed, if all is in order? https://github.com/thundernest/autoconfig/pull/36

Best regards,
[b]

brian cors (he / him)
University of Michigan | Information and Technology Services
Collaboration Services Manager

**Comment by benbucksch** [comment] 2022-06-27 20:47
Thanks for the pull request.

I've tried to query DNS MX umich.edu, but that returns mx1.a.mail.umich.edu , which is either hosted or connected by Amazon, not Google.

Likewise, the official documentation on the website also matches our existing config, not the proposed config here. https://www.getmailbird.com/setup/access-umich-edu-via-imap-smtp 

Can I see some official proof that University of Michigan changed to Google, and that all @umich.edu email accounts are hosted there now, both student and staff accounts, as applicable?

Given that changes in the ISPDB become effective *immediately* (for users who set up new accounts), I would expect the website documentation to be updated first.

Also, what is your plan for existing users who have the current setup? Will they all break?

**Comment by umichbcors** [comment] 2022-06-27 21:09
Hello, Ben!

The documentation that you are pointing to is for a separate, Authenticated SMTP service for use on campus here - and is completely separate from using the Google SMTP servers with individual accounts for all faculty, students, and staff here at Michigan.

I am one of the service managers and super administrators for our Google Workspace domain here at the University of Michigan - and we made the switch to Google long ago here, about ten years ago.

Here is our main website for the Google Workspace service here at Michigan:
https://its.umich.edu/communication/collaboration/google
(My name is on the right side of this page, showing that I am one of the managers for this service.)

Also, here is the archival project page from the migration, almost 10 years ago when we switched over to Google:
https://sites.google.com/a/umich.edu/m-google-project-archive/

My understanding _(please correct me if I am wrong)_ is that this IPDB pulls data on initial configuration of the account within Thunderbird. Right now, anyone who has tried to use the current configuration will not be successful, as the currently published one is from years ago, before U-M moved holistically to Google for our email service.

Also, we are wanting to bring people up to date with using OAuth2 (and their Google account login) to give them a much better onboarding experience, particularly those with accessibility issues with the Google web-based experience.

Please let me know if you have any additional questions or clarifications, and many thanks for your time and assistance.

Best regards,
[b]

brian cors (he / him)
University of Michigan | Information and Technology Services
Collaboration Services Manager

**Comment by umichbcors** [comment] 2022-06-28 14:43
Hello.

**PASSWORD AUTHENTICATION**
With Google turning off the ability to use "Less Secure Apps" in the future, we are shifting people to use OAuth2 solely for login with Thunderbird and other mail clients. Currently, password authentication only works if "Less Secure Apps" are allowed by Google Workspace. We can look to add that info to the configuration file, but it will only work for a while longer, and we will need to update the profile again, once Google completely disallows "Less Secure Apps", to accommodate password authentication.

**SELF-HOSTING**
We understand that this is an option, but would rather not use that path.

**PASSWORD AUTHENTICATION DOCUMENTATION**
We do not have anything publicly posted, as we recommend and only fully support the Google web interface for Gmail. We do need to help people from time to time (as they submit tickets, particularly people with accessibility needs) to get Thunderbird configured. Our hope is that this new configuration file that we are requesting you to update, we will see little to no requests for assistance to get Thunderbird configured and working. I am happy to send you what we do have written for our support staff, via direct email, if you like. Please send me an email to bcors at umich dot edu and I can get those over to you, as desired.

Best regards,
[b]

brian cors (he / him)
University of Michigan | Information and Technology Services
Collaboration Services Manager

**Comment by benbucksch** [comment] 2022-06-28 14:49
Thanks. Email sent

**Comment by umichbcors** [comment] 2022-06-28 15:17
I've not received an email - did you send it to bcors@umich.edu?
I will delete this after I receive it.

**Comment by jamesez** [comment] 2022-07-01 17:25
If it helps - I'm a GitHub enterprise admin for umich-edu, I can confirm @umichbcors is an authority on this service.

**Comment by benbucksch** [comment] 2022-07-06 13:20
@umichbcors : 
* This looks much better.
* I've fixed some more indention problems.
* I've verified the oAuth2 settings that they match Gmail/Google.

I've approved and merged the PR.

It is now on staging https://autoconfig-stage.thunderbird.net/v1.1/umich.edu . Before we deploy it to all users, could you please test it? Please:
* Start Thunderbird with a new profile (preferably, to avoid conflicts with your existing Thunderbird work profile)
* Go to Thunderbird | Settings | General | Advanced config...
* Search for `network.proxy.autoconfig_url`
* Double click on the entry and change the URL to https://autoconfig-stage.thunderbird.net/v1.1/umich.edu
* Go to Menu | New | Existing mail account...
* Set up a @umich.edu test account
* Verify that the IMAP server is now Google 
* Check that you can receive and send mail
* Revert the config change

Once that works, please make a note here, so that I can deploy it to all users.

**Comment by benbucksch** [comment] 2022-07-06 13:23
Sorry, I goofed and gave you the wrong preference setting. The correct one is called `mailnews.auto_config_url`. (I corrected the comment above)

**Comment by benbucksch** [comment] 2022-07-06 13:24
(URL above fixed as well)

**Comment by cketti** [comment] 2023-02-10 12:30
Looks like this was resolved some time ago. Closing the issue.

**Closed by cketti** 2023-02-10 12:30 UTC
